### PR TITLE
Update danish strings.xml

### PR DESCRIPTION
**Pull request by lianergoist**
#### What is it?
- [ ] Bugfix
- [ ] Feature
- [x] Codebase improvement

#### Description of the changes in your PR

- Updated colors
- Update strings
- Added documentation

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
Please don't translate strings that aren't from `app/src/main/res/values/strings.xml`. They aren't meant to be translated.

**Comment by naveensingh** [comment]
@lianergoist ping :)

**Comment by Aga-C** [comment]
There are still strings from [donottranslate.xml](https://github.com/FossifyOrg/Messages/blob/master/app/src/main/res/values/donottranslate.xml).

**Comment by lianergoist** [comment]
Sorry. I will be more careful in the future.

Thomas



fre, 09 02 2024 kl. 22:21 -0800, skrev Agnieszka C:

**Pull request merged**
